---
- hosts: redis
  become: yes
  vars:
    redis_port: 6379
    redis_databases: 1
  tasks:

    - name: Ensure Redis is present
      apt: pkg=redis-server state=latest

    - name: Ensure Redis is started
      service: name=redis-server state=started enabled=yes

    - name: Ensure Redis Configuration
      template: src=redis.conf.j2 dest=/etc/redis/redis.conf owner=root group=root mode=0644
    
    - name: Stop redis-server
      command: /etc/init.d/redis-server stop
   
    - name: Start redis-server
      command: redis-server 

  # handlers:

  #   - name: Redis Restart
  #     service: name=redis-server state=restarted enabled=yes